-- colors/brual.lua

local colors = {
  -- content here will not be touched
  -- PATCH_OPEN
  Normal = { fg = "#C7C7BD", bg = "none" },
  Boolean = { fg = "#E5780B", italic = true },
  CmpItemAbbrDeprecated = { fg = "#696959", bg = "NONE", strikethrough = true },
  CmpItemAbbrMatch = { fg = "#9EF019", bg = "NONE" },
  CmpItemAbbrMatchFuzzy = {},
  CmpItemKindMethod = { link = "CmpItemKindFunction" },
  CmpItemKindUnit = { link = "CmpItemKindKeyword" },
  CmpItemKindProperty = { fg = "#1F9EFF" },
  Comment = { fg = "#696959", italic = true },
  Conceal = { fg = "#C4C4BA" },
  Constant = { fg = "#E52E2E", italic = true },
  CopilotSuggestion = { fg = "#8A8A75" },
  CurSearch = { fg = "#00FF00", bg = "black", bold = true, undercurl = true },
  Cursor = { fg = "#01171E", bg = "#C7C7BD" },
  CursorColumn = {},
  CursorLine = { bg = "#011F27" },
  CursorLineFold = { link = "CursorLine" },
  CursorLineNr = { link = "CursorLine" },
  CursorLineSign = { link = "CursorLine" },
  DapBreakpoint = { bold = true },
  DapBreakpointIcon = { fg = "red", bold = true },
  DapLogPoint = { fg = "#D801F9", bold = true },
  DapStopped = { fg = "#01171E", bg = "#9EF019", bold = true },
  Delimiter = { fg = "#D694FA" },
  DiagnosticError = { fg = "#9F1414" },
  DiagnosticHint = { fg = "#91917E" },
  DiagnosticInfo = { fg = "#1F9EFF" },
  DiagnosticUnderlineError = { sp = "#E52E2E", underdouble = true },
  DiagnosticUnderlineHint = { sp = "#91917E", underdouble = true },
  DiagnosticUnderlineInfo = { sp = "#1F9EFF", underdouble = true },
  DiagnosticUnderlineWarn = { sp = "#F5C024", underdouble = true },
  DiagnosticWarn = { fg = "#BE9109" },
  DiffAdd = { fg = "#9EF019" },
  UndotreeDiffAdded = { link = "DiffAdd" },
  DiffChange = { fg = "#B194FA" },
  DiffDelete = { fg = "#E52E2E" },
  UndotreeDiffRemoved = { link = "DiffDelete" },
  DiffText = { fg = "#E52E2E", bg = "#01171E", bold = true, italic = true, underdotted = true },
  UndotreeDiffLine = { link = "DiffText" },
  Directory = {},
  Encoding = { fg = "#01171E", bg = "#E5780B", bold = true },
  EncodingCap = { fg = "#E5780B", bg = "#01171E", bold = true },
  Error = { fg = "#E52E2E", bg = "#01171E", bold = true },
  Folded = { fg = "#D694FA", bg = "#011F27" },
  Function = { fg = "#F0612D" },
  CmpItemKindFunction = { link = "Function" },
  UndotreeFirstNode = { link = "Function" },
  SnacksIndent = { fg = "#023847" },
  SnacksIndentScope = { fg = "#058DB3" },
  Identifier = { fg = "#E8E8E3" },
  LspReferenceTarget = { underline = true },
  LspReferenceRead = { underline = true },
  LspReferenceWrite = { underline = true },
  LspReferenceText = { underline = true },
  LspInlayHint = { bg = "#023847" },
  CmpItemKindVariable = { link = "Identifier" },
  InsertMode = { fg = "#01171E", bg = "red", bold = true },
  LazyNormal = { fg = "#C7C7BD", bg = "#01171E" },
  LineFeed = { fg = "#01171E", bg = "#D2290F", bold = true },
  LineFeedCap = { fg = "#D2290F", bg = "#01171E", bold = true },
  LineNr = { fg = "#696959" },
  MatchParen = { fg = "#E52E2E" },
  NeoTreeGitUntracked = { fg = "#F0612D" },
  NonText = { fg = "#04617B", italic = true },
  NormalFloat = { fg = "#C7C7BD", bg = "#01171E" },
  Operator = { fg = "#D694FA" },
  Pmenu = { fg = "#C4C4BA", bg = "#01171E" },
  PmenuSel = { fg = "#01171E", bg = "#F5C024", bold = true },
  PreProc = { fg = "#E5780B" },
  Question = { fg = "#9EF019" },
  RainbowDelimiterBlue = { fg = "#1F9EFF" },
  RainbowDelimiterCyan = { fg = "cyan" },
  RainbowDelimiterGreen = { fg = "#9EF019" },
  RainbowDelimiterOrange = { fg = "#F9A201" },
  RainbowDelimiterRed = { fg = "red" },
  RainbowDelimiterViolet = { fg = "#D801F9" },
  RainbowDelimiterYellow = { fg = "#F5C024" },
  RenderMarkdownBullet = { fg = "#fb9f62" },
  RenderMarkdownChecked = { fg = "#9EF019" },
  RenderMarkdownCode = { bg = "#252C2C" },
  RenderMarkdownCodeInline = { bg = "#252C2C" },
  RenderMarkdownDash = { fg = "#9b82cd" },
  RenderMarkdownError = { fg = "#D2290F" },
  RenderMarkdownH1 = { fg = "#87a6e9", bg = "#262626", bold = true },
  RenderMarkdownH1Bg = { fg = "#87a6e9", bg = "#262626", bold = true },
  RenderMarkdownH2 = { fg = "#e7b477", bg = "#262626", bold = true },
  RenderMarkdownH2Bg = { fg = "#e7b477", bg = "#262626", bold = true },
  RenderMarkdownH3 = { fg = "#a9ce85", bg = "#262626", bold = true },
  RenderMarkdownH3Bg = { fg = "#a9ce85", bg = "#262626", bold = true },
  RenderMarkdownH4 = { fg = "#35b29c", bg = "#262626", bold = true },
  RenderMarkdownH4Bg = { fg = "#35b29c", bg = "#262626", bold = true },
  RenderMarkdownH5 = { fg = "#b19be0", bg = "#262626", bold = true },
  RenderMarkdownH5Bg = { fg = "#b19be0", bg = "#262626", bold = true },
  RenderMarkdownH6 = { fg = "#9b82cd", bg = "#262626", bold = true },
  RenderMarkdownH6Bg = { fg = "#9b82cd", bg = "#262626", bold = true },
  RenderMarkdownHint = { fg = "#91917E" },
  RenderMarkdownInfo = { fg = "#1F9EFF" },
  RenderMarkdownLink = { fg = "#1F9EFF" },
  RenderMarkdownMath = { fg = "#9b82cd" },
  RenderMarkdownQuote = { bg = "#252C2C" },
  RenderMarkdownSign = { fg = "#9b82cd" },
  RenderMarkdownSuccess = { fg = "#9EF019" },
  RenderMarkdownTableFill = { fg = "#9b82cd" },
  RenderMarkdownTableHead = { fg = "#E54910" },
  RenderMarkdownTableRow = { fg = "#E54910" },
  RenderMarkdownTodo = { fg = "#1F9EFF" },
  RenderMarkdownUnchecked = { fg = "#91917E" },
  RenderMarkdownWarn = { fg = "#E5780B" },
  RenderMarkdownWikiLink = { fg = "#35b29c" },
  Ruler = { fg = "#01171E", bg = "#7CB375", bold = true },
  RulerCap = { fg = "#7CB375", bg = "#01171E", bold = true },
  Search = { fg = "#F5C024", bg = "#011F27", bold = true, undercurl = true },
  TelescopeMatching = { link = "Search" },
  Session = { fg = "#01171E", bg = "#7CB375", bold = true },
  SignColumn = {},
  Size = { fg = "#01171E", bg = "#B194FA", bold = true },
  SizeCap = { fg = "#B194FA", bg = "#01171E", bold = true },
  Special = { fg = "#D694FA" },
  Statement = { fg = "#B194FA", italic = true },
  CmpItemKindKeyword = { link = "Statement" },
  StatusLine = { fg = "#7CB375", bold = true },
  StatusLineNC = { fg = "#01171E", bg = "#B194FA", bold = true },
  String = { fg = "#F5C024", italic = true },
  CmpItemKindText = { link = "String" },
  TabLine = { fg = "#01171E", bg = "#886806", bold = true },
  TabLineErr = { fg = "#01171E", bg = "#9F1414", bold = true },
  TabLineErrSel = { fg = "#01171E", bg = "red", bold = true },
  TabLineFill = { fg = "#F5C024", bg = "none" },
  TabLineOK = { fg = "#01171E", bg = "#9EF019", bold = true },
  TabLineSel = { fg = "#01171E", bg = "#F5C024", bold = true },
  TabLineWarn = { fg = "#01171E", bg = "#AF5C08", bold = true },
  TabLineWarnSel = { fg = "#01171E", bg = "#E5780B", bold = true },
  TelescopePreviewBorder = { fg = "#1F9EFF", bg = "#01171E" },
  TelescopePreviewNormal = { bg = "#01171E" },
  TelescopePreviewTitle = { fg = "#1F9EFF", bg = "#01171E" },
  TelescopePromptBorder = { fg = "#1F9EFF", bg = "#01171E" },
  TelescopePromptNormal = { fg = "#1F9EFF", bg = "#01171E" },
  TelescopePromptTitle = { fg = "#9EF019", bg = "#01171E" },
  TelescopeResultsBorder = { fg = "#1F9EFF", bg = "#01171E" },
  TelescopeResultsNormal = { fg = "#C4C4BA", bg = "#01171E" },
  TelescopeResultsTitle = { fg = "#1F9EFF", bg = "#01171E" },
  TelescopeSelection = { fg = "#01171E", bg = "#F5C024" },
  Title = { fg = "#7CB375" },
  TreesitterContext = { fg = "#696959", bg = "none" },
  TreesitterContextLineNumber = { fg = "#696959", bg = "none" },
  TreesitterContextSeparator = { fg = "#696959", bg = "none" },
  Type = { fg = "#7CB375", italic = true },
  CmpItemKindInterface = { link = "Type" },
  UndotreeBranch = { fg = "#B194FA" },
  UndotreeTimeStamp = { fg = "#C4C4BA" },
  VertSplit = { fg = "#476C5A" },
  Visual = { fg = "#01171E", bg = "#F5C024", bold = true },
  WarningMsg = { fg = "#E52E2E" },
  Whitespace = { fg = "#04617B" },
  ["@constant"] = { fg = "#9EF019" },
  ["@keyword.operator.typescript"] = { fg = "#E54910", italic = true },
  ["@lsp.type.property.lua"] = { fg = "#1F9EFF" },
  ["@markup.link.label.markdown_inline"] = { fg = "#1F9EFF" },
  ["@method"] = { fg = "#E5780B", bold = true },
  ["@method.vue"] = { fg = "#7AC6FF", italic = true },
  ["@parameter"] = { fg = "#E54910" },
  ["@property"] = { fg = "#1F9EFF" },
  ["@punctuation"] = { fg = "#D694FA" },
  ["@punctuation.special.vue"] = { fg = "#1F9EFF" },
  ["@tag"] = { fg = "#D694FA" },
  ["@tag.attribute.vue"] = { fg = "#1F9EFF" },
  ["@type.typescript"] = { fg = "#F9A201", italic = true },
  ["@variable.javascript"] = { fg = "#E54910" },
  -- PATCH_CLOSE
  -- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='brutal'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
